name: ariyanpay
description: Flutter package for AriyanPay by Ariyan Shipu — a custom payment gateway integration for Flutter apps.
version: 0.0.6
homepage: https://ariyanshipu.me
repository: https://github.com/ariyanshiputech/ariyanpay
issue_tracker: https://github.com/ariyanshiputech/ariyanpay/issues
documentation: https://youtube.com/@ariyanshiputech
example: https://github.com/ariyanshiputech/ariyanpay/tree/master/example
# Publish to pub.dev (set to false if private)
publish_to: 'https://pub.dev'
topics:
  - flutter
  - payment
  - ariyanpay
  - ariyanshipu
  - gateway


environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.6"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  webview_flutter: ^2.0.13
  get: ^4.6.6
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Uncomment and add your assets if needed in future
  # assets:
  #   - images/

  # Uncomment and add your custom fonts if needed in future
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
